/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.saloonsayoma.Views.lasith;


import com.sliit.saloonsayoma.utils.DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.*;

/**
 *
 * @author LasithD
 */
public class CreditClientReg extends javax.swing.JPanel {
    Connection con =null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    /**
     * Creates new form NewJPanel
     */
    public CreditClientReg() {
        initComponents();
        
        con = DB.getConnection();
        
        try{
            rs= DB.getResultSet("select * from creditclient");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
             
            }
        
        catch(Exception e)  {
            
            JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
            
           
                            }
    
        try{
            
             ResultSet rs1 =null;
            
            
            rs1=  DB.getResultSet("select max(idCreditClient) from creditclient");
            while(rs1.next()){
            int value = rs1.getInt(1);            
            int nexicid = value+1;           
            String Conid = Integer.toString(nexicid);           
            cidbox.setText(Conid);
            
            
                              }
            }
        
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
            
                            }  
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cidbox = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cnamebox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailbox = new javax.swing.JTextField();
        pnobox = new javax.swing.JTextField();
        nicbox = new javax.swing.JTextField();
        climitbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressbox = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searcbox = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Registration for Credit Facility ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Customer ID");

        cidbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cidbox.setForeground(new java.awt.Color(0, 153, 153));
        cidbox.setText(".");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Customer Name");

        cnamebox.setText(" ");
        cnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameboxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("E-mail");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Phone Number");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("NIC");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Address");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Credit Limit");

        emailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailboxActionPerformed(evt);
            }
        });

        pnobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnoboxActionPerformed(evt);
            }
        });

        nicbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicboxActionPerformed(evt);
            }
        });

        addressbox.setColumns(20);
        addressbox.setRows(5);
        jScrollPane1.setViewportView(addressbox);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                " ID", " Name", "TP", "NIC", "Credit Limit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        searcbox.setForeground(new java.awt.Color(0, 0, 153));
        searcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search By", "CID", "Name", "Nic", "Address", "TP", " " }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Credit Client Details ");

        jButton6.setForeground(new java.awt.Color(0, 0, 153));
        jButton6.setText("Sarch");

        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setForeground(new java.awt.Color(0, 0, 153));
        jButton5.setText("EDIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setForeground(new java.awt.Color(0, 0, 153));
        jButton7.setText("RESET");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setForeground(new java.awt.Color(0, 0, 153));
        jButton8.setText("DELETE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 484, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailbox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnobox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nicbox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cnamebox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cidbox)
                            .addComponent(climitbox, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searcbox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 710, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cidbox))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pnobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nicbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(climitbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
     public void resetData() 
    {
    
       // cidbox.setText("");
        cnamebox.setText("");
        emailbox.setText("");
        pnobox.setText("");
        nicbox.setText("");
        addressbox.setText("");
        climitbox.setText("");
        searcbox.setSelectedItem("Search By");
        jTextField6.setText("");

    }
    
    private void cnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameboxActionPerformed

    private void emailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailboxActionPerformed

    private void nicboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicboxActionPerformed

    private void pnoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnoboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnoboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                
                 String CID =cidbox.getText();
                 String CNAME =cnamebox.getText();
                 String EMAIL =emailbox.getText();
                 String PNO =pnobox.getText();
                 String NIC =nicbox.getText();
                 String ADDRES =addressbox.getText();
                 String CRELIM =climitbox.getText();
                 String CredtLim =climitbox.getText();
               
         
                 //Add Cclient Details
                  Cclient c = new Cclient(CID, CNAME,EMAIL,PNO,NIC,ADDRES,CRELIM,CredtLim);
                c.AddCclient();
                   
                //Get Table Data
                try{
                     rs= DB.getResultSet("select * from creditclient");
                     jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                     }
        
        catch(Exception e)  {
            
            JOptionPane.showMessageDialog(null,"Unable to Retrieve Data", "Error", JOptionPane.ERROR_MESSAGE);
                            }
 
                resetData(); 
                
                try{
            
                        ResultSet rs2 =null;
            
            
                         rs2=  DB.getResultSet("select max(idCreditClient) from creditclient");
          
                         while(rs2.next()){
                         int value = rs2.getInt(1);
                         int nexicid = value+1;
                         String Conid = Integer.toString(nexicid);
                         cidbox.setText(Conid);
            }
        }
        
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
            
                           }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

                 String CNAME =cnamebox.getText();
                 String EMAIL =emailbox.getText();
                 String PNO =pnobox.getText();
                 String NIC =nicbox.getText();
                 String ADDRES =addressbox.getText();
                 String CRELIM =climitbox.getText();



            //compare change done or not
            int ro = jTable1.getSelectedRow();
        
            String cname = jTable1.getValueAt(ro,1).toString();
            boolean b=CNAME.equals(cname);
        
             String email  = jTable1.getValueAt(ro,2).toString();
            boolean c=EMAIL.equals(email);
        
             String pno  = jTable1.getValueAt(ro,3).toString();
              boolean d=PNO.equals(pno);
        
             String nic = jTable1.getValueAt(ro,4).toString();
            boolean e=NIC.equals(nic);
        
             String address  = jTable1.getValueAt(ro,5).toString();
             boolean f=ADDRES.equals(address);
   
             String crlim   = jTable1.getValueAt(ro,5).toString();
             boolean g=CRELIM.equals(crlim);
            

/*
if((b==false)||(c == false)||(d==false)||(e==false)||(f==false)||(g ==false))
                        {               //validate data
                                      
                                         {  int co= JOptionPane.showConfirmDialog(null,"DO YOU WANT TO UPDATE THIS RECORD?");

                                             if(co==0)
                                                     {

                                                              Cclient c1 = new Cclient(CID, CNAME,EMAIL,PNO,NIC,ADDRES,CRELIM,CredtLim);
                                                                  c1.

                                                                 try 
                                                                 {
                                                                 String sql=p2.GetPatientDetail();
                                                                 pst=con.prepareStatement(sql);
                                                                 rs = pst.executeQuery(); 
                                                                 jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                                                 } 

                                                                 catch (Exception ex) 
                                                                 {
                                                                   JOptionPane.showMessageDialog(null,"Unable to Retrieve Data", "Error", JOptionPane.ERROR_MESSAGE);

                                                                 }

                                                                 resetData();
                                                     }


                                             if (co==1)
                                                     {

                                                                 String st="UPDATE CANCELLED";
                                                                 JOptionPane.showMessageDialog(null,st); 
                                                     }

                                         
                                         }                                      
                            }                            
                 else 
                            { 
                             String st="YOU HAVEN’T CHANGE ANYTHING";
                             JOptionPane.showMessageDialog(null,st);
                             }





*/

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
              resetData();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       //get data
        String pcid =cidbox.getText();
        String pnic=nicbox.getText();
        
       boolean a =pcid.isEmpty();
       boolean b=pnic.isEmpty();   
if((a==false)&&(b==false))
{
        int co= JOptionPane.showConfirmDialog(null,"DO YOU WANT TO DELETE THIS RECORD?");

            if(co==0)
               {            
                            Cclient c3 = new Cclient(pcid,pnic);
                            c3.DeletePatient();
                            
                             try 
                             {
                                 rs= DB.getResultSet("select * from creditclient");
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                 resetData();
                                 } 

                             catch (Exception e) 
                              {
                                JOptionPane.showMessageDialog(null,"Unable to Retrieve Data", "Error", JOptionPane.ERROR_MESSAGE);

                               }
                             
                
                             try{
            
                                 ResultSet rs1 =null;
            
            
                                rs1=  DB.getResultSet("select max(idCreditClient) from creditclient");
                                while(rs1.next()){
                                int value = rs1.getInt(1);            
                                int nexicid = value+1;           
                                String Conid = Integer.toString(nexicid);           
                                cidbox.setText(Conid);
                                                 }
                                }
                 catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
            
                                    }                    
                     
               }
       
            if (co==1)
                {

                        String st="DELETION CANCELLED";
                        JOptionPane.showMessageDialog(null,st); 
                }

}

else
{
    String st="SELECT PATIENT FOR DELETE";
    JOptionPane.showMessageDialog(null,st); 
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        resetData();
        int r = jTable1.getSelectedRow();
         
        String CCID  = jTable1.getValueAt(r,0).toString();
        String CNAMET = jTable1.getValueAt(r,1).toString();
        String CEMAIL  = jTable1.getValueAt(r,2).toString();
        String CPHONE  = jTable1.getValueAt(r,3).toString();
        String CNIC = jTable1.getValueAt(r,4).toString();
        String CADDRESS  = jTable1.getValueAt(r,5).toString();
        String CLIM  = jTable1.getValueAt(r,6).toString();

        
        cidbox.setText(CCID);
        cnamebox.setText(CNAMET);
        emailbox.setText(CEMAIL);
        pnobox.setText(CPHONE);
        nicbox.setText(CNIC);
        addressbox.setText(CADDRESS);
        climitbox.setText(CLIM);

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressbox;
    private javax.swing.JLabel cidbox;
    private javax.swing.JTextField climitbox;
    private javax.swing.JTextField cnamebox;
    private javax.swing.JTextField emailbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField nicbox;
    private javax.swing.JTextField pnobox;
    private javax.swing.JComboBox<String> searcbox;
    // End of variables declaration//GEN-END:variables
}
