/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.saloonsayoma.Views.lasith;

import com.sliit.saloonsayoma.Views.App;
import com.sliit.saloonsayoma.utils.DB;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.*;

/**
 *
 * @author LasithD
 */
public class Sales extends javax.swing.JPanel {

    Connection con =null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    /**
     * Creates new form Sale
     */
    public Sales() {
        initComponents();
        
          con = DB.getConnection();
        
        try{
            rs= DB.getResultSet("select idproducts,pname,quantity,sprice From products");
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
             
            }
        
        catch(Exception e)  {
            
            JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
            
           
                            }
        
        try{
            
             ResultSet rs1 =null;
            
            
            rs1=  DB.getResultSet("select max(idOrder) from orders");
            while(rs1.next()){
            int value = rs1.getInt(1);            
            int nexicid = value+1;           
            String Conid = Integer.toString(nexicid);           
            billnubox.setText(Conid);

                              }
            }
        
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
            
                            } 
        
        
       DateFormat df = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
       Date dateobj = new Date();
       
       datebox.setText(convertStringToDate(dateobj));
       
                            
       String idget = billnubox.getText();
                                    try{
                                      rs= DB.getResultSet("select i.pid,i.Dis,p.sprice,i.Qty,i.SubTot from itemdetails i,products p where p.idproducts=i.pid AND i.Oid ='"+idget+"'");
                                      jTable1.setModel(DbUtils.resultSetToTableModel(rs));

                                      }

                                    catch(Exception e) {

                                     JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);


                                                   }
                                    
                                    
nuofitembox.setText(Integer.toString(getsum()));
        totamountbox.setText(String.format( "%.2f", getsumprice()));
        
    }

    
    
  
          
  public String convertStringToDate(Date indate)
    {
   String dateString = null;
   SimpleDateFormat sdfr = new SimpleDateFormat("dd/MMM/yyyy");
   /*you can also use DateFormat reference instead of SimpleDateFormat 
    * like this: DateFormat df = new SimpleDateFormat("dd/MMM/yyyy");
    */
   try{
	dateString = sdfr.format( indate );
   }catch (Exception ex ){
	System.out.println(ex);
   }
   return dateString;
}
    
    public void resetData() 
    {
    
       // cidbox.setText("");
        iidbox.setText("");
        disbox.setText("");
        upricebox.setText("");
        Qbox.setText("");
        subtotbox.setText("");
    }
    
  public boolean isInteger( String input )
{
            try
            {
               Integer.parseInt( input );
               return true;
            }
            catch( Exception e)
            {
               return false;
            }
}
  
  public int getsum()
  {
      int rowCount = jTable1.getRowCount();
      int sum = 0;
      for (int i = 0; i < rowCount; i++) 
      {
          sum =sum+Integer.parseInt(jTable1.getValueAt(i, 3).toString());
       }
      
      return sum;
      
  }
  
    /**
     *
     * @return
     */
    public double getsumprice()
  {
      double rowCount = jTable1.getRowCount();
      double sum = 0;
      for (int i = 0; i < rowCount; i++) 
      {
          sum =sum+Integer.parseInt(jTable1.getValueAt(i, 4).toString());
       }
      
      return sum;
      
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cnamebox = new javax.swing.JTextField();
        billnubox = new javax.swing.JLabel();
        datebox = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        iidbox = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        disbox = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        upricebox = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Qbox = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        subtotbox = new javax.swing.JLabel();
        keybox = new javax.swing.JTextField();
        searcbox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        fwk = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nuofitembox = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        totamountbox = new javax.swing.JLabel();
        disorecentage = new javax.swing.JTextField();
        disamount = new javax.swing.JLabel();
        netvalue = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        Cash = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        Bal = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Cosmetic Sales  ");

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATE      :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BILL NO :");

        Cnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnameboxActionPerformed(evt);
            }
        });

        billnubox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        billnubox.setForeground(new java.awt.Color(255, 255, 255));
        billnubox.setText("4");

        datebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        datebox.setForeground(new java.awt.Color(255, 255, 255));
        datebox.setText("15/10/2014");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(datebox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(billnubox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(Cnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billnubox))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(datebox))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ITEM ID", "DISCRIPTION", "PRICE", "QUANTITY", "SUBTOTAL "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("ITEM ID");

        iidbox.setBackground(new java.awt.Color(153, 204, 255));
        iidbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        iidbox.setText("ITEM ID");
        iidbox.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ITEM ID", "DISCRIPTION", "PRICE", "STOCK LEVEL "
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("DISCRIPTION");

        disbox.setBackground(new java.awt.Color(153, 204, 255));
        disbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        disbox.setText("DISCRIPTION");
        disbox.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setBackground(new java.awt.Color(204, 204, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("UNIT PRICE");

        upricebox.setBackground(new java.awt.Color(153, 204, 255));
        upricebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        upricebox.setText("UNIT PRICE");
        upricebox.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("QUANTITY");

        Qbox.setBackground(new java.awt.Color(153, 204, 255));
        Qbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Qbox.setText("UNIT PRICE");
        Qbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QboxActionPerformed(evt);
            }
        });
        Qbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QboxKeyPressed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(204, 204, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("SUBTOTAL ");

        subtotbox.setBackground(new java.awt.Color(153, 204, 255));
        subtotbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        subtotbox.setText("SUBTOTAL ");
        subtotbox.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        searcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "ITEM_ID", "DISCRIPTION", " " }));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 153));
        jButton4.setText("REMOVE ITEM ");
        jButton4.setActionCommand("REMOVE ITEM ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 153));
        jButton5.setText("CONFIRM");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        fwk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fwk.setForeground(new java.awt.Color(0, 0, 153));
        fwk.setText("TOTAL AMOUNT ");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("DISCOUT (%)");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setText("DISCOUNT AMOUNT");

        nuofitembox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nuofitembox.setText("                          ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 153));
        jLabel23.setText("NET SALES ACOUNT ");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 153));
        jLabel26.setText("NU. OF ITEMS");

        totamountbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totamountbox.setText("                      ");

        disorecentage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        disorecentage.setText("0");
        disorecentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                disorecentageKeyPressed(evt);
            }
        });

        disamount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        disamount.setText("                           ");

        netvalue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        netvalue.setText("                         ");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 153));
        jButton6.setText("UPDATE QTY");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 153));
        jButton7.setText("PRINT ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 153));
        jLabel27.setText("CASH");

        Cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashActionPerformed(evt);
            }
        });
        Cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CashKeyPressed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 153));
        jLabel28.setText("BALANCE");

        Bal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bal.setForeground(new java.awt.Color(255, 51, 51));
        Bal.setText("                               ");

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 153));
        jButton8.setText("ORDER RECORDS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel7))
                                            .addComponent(iidbox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel9))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(disbox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel11)
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel13)
                                                .addGap(54, 54, 54)
                                                .addComponent(jLabel14))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(upricebox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8)
                                                .addComponent(Qbox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(subtotbox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(30, 30, 30)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searcbox, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(keybox, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton1))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel20)
                                            .addComponent(fwk)))
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(netvalue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nuofitembox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(disamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totamountbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(disorecentage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bal))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iidbox)
                    .addComponent(disbox)
                    .addComponent(upricebox)
                    .addComponent(Qbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotbox))
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(netvalue)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(keybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuofitembox)
                            .addComponent(jLabel26))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totamountbox, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fwk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(disorecentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(Bal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(disamount))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnameboxActionPerformed

    private void QboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QboxActionPerformed

    private void QboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QboxKeyPressed


        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
              

        String en = iidbox.getText();
        String en1 = disbox.getText();
        String en4 = Qbox.getText();
        String en5 = subtotbox.getText();
        String en6 = billnubox.getText();
        String en7= upricebox.getText();
        String en8 =billnubox.getText();
      
        boolean a =isInteger(en4);
        boolean b =en4.isEmpty();
        boolean c =en4.equals("0");
            
        
       
        if(b==true)
        {
            
            JOptionPane.showMessageDialog(null,"QUANTITY CANNOT BE EMPTY", "Error", JOptionPane.ERROR_MESSAGE);
        }
              
        else if(c==true)
         {
                JOptionPane.showMessageDialog(null,"QUANTITY CANNOT BE '0' ", "Error", JOptionPane.ERROR_MESSAGE);
                
         }     
          
        else if(a==false)
        {
            JOptionPane.showMessageDialog(null,"PLESE ENTER NUMBER", "Error", JOptionPane.ERROR_MESSAGE);
        }

       else
       
        {
                int foo = Integer.parseInt(en4);
                int fo = Integer.parseInt(en7);
                int sum = (foo*fo);

                String str = Integer.toString(sum);
                subtotbox.setText(str);
                
               con =DB.getConnection();
        
         try{
                String pq="INSERT INTO itemdetails(Oid,Pid,Qty,SubTot,Dis)Values('"+en6+"','"+en+"','"+en4+"','"+sum+"','"+en1+"')";
                pst=con.prepareStatement(pq);
                pst.execute();
                String st="SUCCESSFULLY ADDED";
                JOptionPane.showMessageDialog(null,st);
                
                
            } 
         
        catch (Exception e) 
            {
               
               JOptionPane.showMessageDialog(null,"ITEM ALREADY EXISTS", "Error", JOptionPane.ERROR_MESSAGE);

            }
         
     
                                try{
                                      rs= DB.getResultSet("select i.pid,i.Dis,p.sprice,i.Qty,i.SubTot from itemdetails i,products p where p.idproducts=i.pid and i.Oid ='"+en6+"'" );
                                      jTable1.setModel(DbUtils.resultSetToTableModel(rs));

                                      }

                                catch(Exception e)  {

                                      JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);


                                                      }
       
      
        }
        
                nuofitembox.setText(Integer.toString(getsum())); 
               totamountbox.setText(String.format( "%.2f", getsumprice()));
        
                String tot= totamountbox.getText();
                String dis=disorecentage.getText();
                
                Double f = Double.parseDouble(tot);
                Double f1 = Double.parseDouble(dis);
               
               Double disamt = (f*(f1/100));
               Double net =(f-disamt);
               
               System.out.println(tot);
               
               disamount.setText(String.format( "%.2f", disamt)); 
               netvalue.setText(String.format( "%.2f", net));
               
               
   }
            

        // TODO add your handling code here:
    }//GEN-LAST:event_QboxKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            con =DB.getConnection();
            String i1 =iidbox.getText();
            String i2 =billnubox.getText();
            

        int co= JOptionPane.showConfirmDialog(null,"DO YOU WANT TO DELETE THIS RECORD?");
        
        boolean c =i1.equals("ITEM ID");
        
        if(c==false)
        {
            if(co==0)
               {
                               try {
                               String pq="DELETE FROM itemdetails WHERE Pid ='"+i1+"'AND Oid ='"+i2+"'";
                               System.out.println(pq);
                               pst=con.prepareStatement(pq);
                               pst.execute();
                                   System.out.println("DELETE FROM itemdetails WHERE Pid ='"+i1+"'AND Oid ='"+i2+"'");
                               String st="SUCCESSFULLY DELETED";
                               JOptionPane.showMessageDialog(null,st);
                               
                               
                                               } 
         
        catch (Exception e)  
                            {
                                JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
                            }
         
                            
                             try{
                                      rs= DB.getResultSet("select i.pid,i.Dis,p.sprice,i.Qty,i.SubTot from itemdetails i,products p where p.idproducts=i.pid and i.Oid ='"+i2+"'" );               
                                      jTable1.setModel(DbUtils.resultSetToTableModel(rs));

                                      }

                                catch(Exception e)  {

                                      JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
               }
       
            if (co==1)
                {

                        String st="DELETION CANCELLED";
                        JOptionPane.showMessageDialog(null,st); 
          
                
             }
                nuofitembox.setText(Integer.toString(getsum())); 
               totamountbox.setText(String.format( "%.2f", getsumprice()));
        
                String tot= totamountbox.getText();
                String dis=disorecentage.getText();
                
                Double f = Double.parseDouble(tot);
                Double f1 = Double.parseDouble(dis);
               
               Double disamt = (f*(f1/100));
               Double net =(f-disamt);
               
               System.out.println(tot);
               
               disamount.setText(String.format( "%.2f", disamt)); 
               netvalue.setText(String.format( "%.2f", net));
        }       
           
     }
        else{
            String st="SELECT ONLY THE ITEM IN ORDER";
            JOptionPane.showMessageDialog(null,st);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        String v = Cnamebox.getText();
        String v2 = totamountbox.getText();
        String v3 = nuofitembox.getText();
        String v4 = disorecentage.getText();
        String v5 = disamount.getText();
  
       Double a = Double.parseDouble(v2);
       boolean b = v2.isEmpty();
       
        if(a!=0.0||b==true)
        {
        try{
    
                String pq="INSERT INTO orders(Cname,totval,ToQty,dispra,disamount)Values('"+v+"','"+v2+"','"+v3+"','"+v4+"','"+v5+"')";
                System.out.println(pq);
                pst=con.prepareStatement(pq);
                pst.execute();
                String st="SUCCESSFULLY CONFIRMED";
                JOptionPane.showMessageDialog(null,st);
                
                
            } 
         
        catch (Exception e) 
            {
               
               JOptionPane.showMessageDialog(null,"ORDER NOT CONFIRMED", "Error", JOptionPane.ERROR_MESSAGE);

            }
            
            
            try{
            
             ResultSet rs1 =null;
            
            
            rs1=  DB.getResultSet("select max(idOrder) from orders");
            while(rs1.next()){
            int value = rs1.getInt(1);            
            int nexicid = value+1;           
            String Conid = Integer.toString(nexicid);           
            billnubox.setText(Conid);

                              }
            }
        
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
            
                            }

             try{
                                     String p =billnubox.getText();
                                     rs= DB.getResultSet("select i.pid,i.Dis,p.sprice,i.Qty,i.SubTot from itemdetails i,products p where p.idproducts=i.pid and i.Oid ='"+p+"'" );
                                      jTable1.setModel(DbUtils.resultSetToTableModel(rs));

                                      }

                                catch(Exception e)  {

                                      JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);


                                                      }


 
       nuofitembox.setText("0");
        totamountbox.setText("0");
        disorecentage.setText("0");
       disamount.setText("0");
        netvalue.setText("0");
       Cash.setText("");
       Bal.setText("0");
        }
        
        else{
            
            JOptionPane.showMessageDialog(null,"ORDER NOT CONFIRMED", "Error", JOptionPane.ERROR_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            
            con =DB.getConnection();
            String i1 =iidbox.getText();
            String i2 =billnubox.getText();
            String i3 =Qbox.getText();
            String i4 =upricebox.getText();
            
            
                               Integer g = Integer.parseInt(i3);
                               Integer g1 = Integer.parseInt(i4);
                                
                               Integer d =(g*g1);
                               
                               String str =Integer.toString(d);
            
                              subtotbox.setText(str); 
                              String i5 =subtotbox.getText();
        
int co= JOptionPane.showConfirmDialog(null,"DO YOU WANT TO UPDATE THIS RECORD?");
        
            if(co==0)
               {
                               try {
                               String pq="UPDATE itemdetails SET Qty ='"+i3+"',SubTot ='"+i5+"' WHERE Pid ='"+i1+"'AND Oid ='"+i2+"'";
                               System.out.println(pq);
                               pst=con.prepareStatement(pq);
                               pst.execute();
                               String st="SUCCESSFULLY UPDATED";
                               JOptionPane.showMessageDialog(null,st);
                               
                               
                                               } 
         
        catch (Exception e)  
                            {
                                JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
                            }
         
                            
                             try{
                                      rs= DB.getResultSet("select i.pid,i.Dis,p.sprice,i.Qty,i.SubTot from itemdetails i,products p where p.idproducts=i.pid and i.Oid ='"+i2+"'" );               
                                      jTable1.setModel(DbUtils.resultSetToTableModel(rs));

                                      }

                                catch(Exception e)  {

                                      JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
               }
       
            if (co==1)
                {

                        String st="UPDATION CANCELLED";
                        JOptionPane.showMessageDialog(null,st); 
          
                
             }
               
               nuofitembox.setText(Integer.toString(getsum())); 
               totamountbox.setText(String.format( "%.2f", getsumprice()));
        
                String tot= totamountbox.getText();
                String dis=disorecentage.getText();
                
                Double f = Double.parseDouble(tot);
                Double f1 = Double.parseDouble(dis);
               
               Double disamt = (f*(f1/100));
               Double net =(f-disamt);
               
               System.out.println(tot);
               
               disamount.setText(String.format( "%.2f", disamt)); 
               netvalue.setText(String.format( "%.2f", net));
           
        }       
                
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        con = DB.getConnection();
        
        String psearcbox =searcbox.getSelectedItem().toString();
        

       
        
        
        
        if(psearcbox.equals("ITEM_ID"))
        {
                    try
                    {
                     String pkeybox=keybox.getText();
                     rs = DB.getResultSet("SELECT idproducts,pname,quantity,sprice From products WHERE idproducts LIKE '%"+pkeybox+"%'" );
                    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                    catch (Exception e) 
                    {
                        JOptionPane.showMessageDialog(null,"Unable to Retrieve Data", "Error", JOptionPane.ERROR_MESSAGE);
                    }

        }
        

        else if(psearcbox.equals("ALL"))
        {
            try
                    {
                     keybox.setText("");
                     rs = DB.getResultSet("SELECT idproducts,pname,quantity,sprice From products" );
                    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                    catch (Exception e) 
                    {
                        JOptionPane.showMessageDialog(null,"Unable to Retrieve Data", "Error", JOptionPane.ERROR_MESSAGE);
                    }
            
        }
        
        else{
            
            try
                    {
                     String pkeybox=keybox.getText();
                     rs = DB.getResultSet("SELECT idproducts,pname,quantity,sprice From products WHERE pname LIKE '%"+pkeybox+"%'" );
                    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                    catch (Exception e) 
                    {
                        JOptionPane.showMessageDialog(null,"Unable to Retrieve Data", "Error", JOptionPane.ERROR_MESSAGE);
                    }
            }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

         resetData();
        int r = jTable2.getSelectedRow();
         
        String IID  = jTable2.getValueAt(r,0).toString();
        String IDIS = jTable2.getValueAt(r,1).toString();
        String IPRICE  = jTable2.getValueAt(r,3).toString();
        
       
        iidbox.setText(IID);
        disbox.setText(IDIS);
        upricebox.setText(IPRICE);
        Qbox.setText("1");
        
        String sa= upricebox.getText();
        String sb=Qbox.getText();
    
            int foo = Integer.parseInt(sa);
            int fo = Integer.parseInt(sb);
       
                int sum = (foo*fo);
       
                String str = Integer.toString(sum);
       
                subtotbox.setText(str);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void disorecentageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_disorecentageKeyPressed


if(evt.getKeyCode() == KeyEvent.VK_ENTER){
              
        String tot= totamountbox.getText();
        String dis=disorecentage.getText();
       
          
        boolean a =isInteger(dis);
        boolean b =tot.isEmpty();
        boolean c =dis.equals("0");

        if(b==true)
        {
            
            JOptionPane.showMessageDialog(null,"DISCOUNT CANNOT BE EMPTY", "Error", JOptionPane.ERROR_MESSAGE);
        }
              
        else if(c==true)
         {
                JOptionPane.showMessageDialog(null,"DISCOUNT IS  0%", "Error", JOptionPane.ERROR_MESSAGE);
                
         }     
          
        else if(a==false)
        {
            JOptionPane.showMessageDialog(null,"PLESE ENTER NUMBER", "Error", JOptionPane.ERROR_MESSAGE);
        }

       else
       
        {
            
               
               Double f = Double.parseDouble(tot);
               Double f1 = Double.parseDouble(dis);
              
               
               Double disamt = (f*(f1/100));
               
              Double net =(f-disamt);
               
               

               disamount.setText(String.format( "%.2f", disamt)); 
               netvalue.setText(String.format( "%.2f", net)); 
                
                
                
               
        }

}
        // TODO add your handling code here:
    }//GEN-LAST:event_disorecentageKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void CashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CashActionPerformed

    private void CashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CashKeyPressed


if(evt.getKeyCode() == KeyEvent.VK_ENTER){
              
        String val= Cash.getText();
        String val2= netvalue.getText();
       
  
        boolean a =isInteger(val);
        boolean b =val.isEmpty();
        boolean c =val2.isEmpty();
        
       Double f = Double.parseDouble(val2);
       Double f1 = Double.parseDouble(val);
        
        if(b==true||a==false)
        {
            
            JOptionPane.showMessageDialog(null,"PLEASE ENTER VALID VALUE", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
        else if (c==true)
                {
                   JOptionPane.showMessageDialog(null,"INVALID OPORATION ", "Error", JOptionPane.ERROR_MESSAGE); 
                }
        
        
       else if(f1<f)
        {
                    JOptionPane.showMessageDialog(null,"MONEY NOT ENOUGH  ", "Error", JOptionPane.ERROR_MESSAGE); 
        }
        
        else 
         {
               
               Double Balance = (f1-f);
               Bal.setText(String.format( "%.2f", Balance));           
         }     
          
}

        // TODO add your handling code here:
    }//GEN-LAST:event_CashKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked


int r = jTable1.getSelectedRow();
         
        String IID  = jTable1.getValueAt(r,0).toString();
        String IDIS = jTable1.getValueAt(r,1).toString();
        String IPRICE  = jTable1.getValueAt(r,2).toString();
        String QTY  = jTable1.getValueAt(r,3).toString();
        String Sub  = jTable1.getValueAt(r,4).toString();
        
        iidbox.setText(IID);
        disbox.setText(IDIS);
        upricebox.setText(IPRICE);
        Qbox.setText(QTY);
        subtotbox.setText(Sub);

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed


        App.showView("viewOrder");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bal;
    private javax.swing.JTextField Cash;
    private javax.swing.JTextField Cnamebox;
    private javax.swing.JTextField Qbox;
    private javax.swing.JLabel billnubox;
    private javax.swing.JLabel datebox;
    private javax.swing.JLabel disamount;
    private javax.swing.JLabel disbox;
    private javax.swing.JTextField disorecentage;
    private javax.swing.JLabel fwk;
    private javax.swing.JLabel iidbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField keybox;
    private javax.swing.JLabel netvalue;
    private javax.swing.JLabel nuofitembox;
    private javax.swing.JComboBox<String> searcbox;
    private javax.swing.JLabel subtotbox;
    private javax.swing.JLabel totamountbox;
    private javax.swing.JLabel upricebox;
    // End of variables declaration//GEN-END:variables
}
