/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.saloonsayoma.Views.stock;

import com.sliit.saloonsayoma.Views.App;
import com.sliit.saloonsayoma.utils.DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.*;

/**
 *
 * @author Ashan
 */
public class SetStock extends javax.swing.JPanel {

   // private String reortderItem;
  //  private String rItem;
    
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet re =null;
    
    

    /**
     * Creates new form SetStock
     */
    public SetStock() {
        initComponents();
        
         con=DB.getConnection(); 
        
         try {
            re = DB.getResultSet("select * from products");
             productstable.setModel(DbUtils.resultSetToTableModel(re));
        } catch (Exception e) {
        }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pidbox = new javax.swing.JTextField();
        pnamebox = new javax.swing.JTextField();
        catbox = new javax.swing.JComboBox<>();
        cidbox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productstable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        notebox = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        stockidbox = new javax.swing.JTextField();
        quantitybox = new javax.swing.JTextField();
        slevlebox = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        spricebox = new javax.swing.JTextField();
        itemscostbox = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbproducts = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stock", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Set Stock Details/Items Registration");

        jLabel3.setText("Product ID");

        jLabel6.setText("Product Name");

        jLabel7.setText("Catergory");

        jLabel5.setText("Stock ID");

        pidbox.setBackground(new java.awt.Color(240, 240, 240));
        pidbox.setPreferredSize(new java.awt.Dimension(6, 24));
        pidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidboxActionPerformed(evt);
            }
        });

        pnamebox.setBackground(new java.awt.Color(240, 240, 240));
        pnamebox.setPreferredSize(new java.awt.Dimension(6, 24));
        pnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameboxActionPerformed(evt);
            }
        });

        catbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Face wash", "Shanpoo", "Lipstick", "Mascara", "Eye Shadow", "Hair Spray" }));
        catbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catboxActionPerformed(evt);
            }
        });

        cidbox.setBackground(new java.awt.Color(240, 240, 240));
        cidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidboxActionPerformed(evt);
            }
        });

        jLabel13.setText("ID");

        productstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Catergory", "Catergory ID", "Product ID", "Product Name", "Stock ID", " Quantity", "Stock Level", "Selling Price", "Item Cost", "Note"
            }
        ));
        productstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productstable);

        jLabel17.setText("Add Quantity");

        notebox.setBackground(new java.awt.Color(240, 240, 240));
        notebox.setPreferredSize(new java.awt.Dimension(6, 24));

        jLabel19.setText("Additional Note");

        jTextField38.setPreferredSize(new java.awt.Dimension(6, 24));
        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel20.setText("Profit");

        jLabel9.setText("Stock Level");

        stockidbox.setBackground(new java.awt.Color(240, 240, 240));
        stockidbox.setPreferredSize(new java.awt.Dimension(6, 24));
        stockidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockidboxActionPerformed(evt);
            }
        });

        quantitybox.setBackground(new java.awt.Color(240, 240, 240));
        quantitybox.setPreferredSize(new java.awt.Dimension(6, 24));
        quantitybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityboxActionPerformed(evt);
            }
        });

        slevlebox.setBackground(new java.awt.Color(240, 240, 240));
        slevlebox.setPreferredSize(new java.awt.Dimension(6, 24));
        slevlebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slevleboxActionPerformed(evt);
            }
        });

        jLabel16.setText("Sale Price");

        spricebox.setBackground(new java.awt.Color(240, 240, 240));
        spricebox.setPreferredSize(new java.awt.Dimension(6, 24));
        spricebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriceboxActionPerformed(evt);
            }
        });

        itemscostbox.setBackground(new java.awt.Color(240, 240, 240));
        itemscostbox.setPreferredSize(new java.awt.Dimension(6, 24));
        itemscostbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemscostboxActionPerformed(evt);
            }
        });

        jLabel21.setText("Item Cost");

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        cmbproducts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Catergory", "cid ", "Stock ID", " " }));
        cmbproducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbproductsActionPerformed(evt);
            }
        });

        txtSearch.setBackground(new java.awt.Color(240, 240, 240));
        txtSearch.setPreferredSize(new java.awt.Dimension(6, 24));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel18.setText("Search by");

        jButton9.setText("Set Catergory");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Retrun Items");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(5, 5, 5)
                .addComponent(cmbproducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(searchButton)
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbproducts, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(searchButton)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Add");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Delete");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Update");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("Print");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel22.setText("Set Re-OrderLevel");

        jButton8.setText("Set ReOrder Level");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel17))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantitybox, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(slevlebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(jButton8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)
                                .addGap(229, 229, 229))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(notebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spricebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(itemscostbox, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(214, 214, 214))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pidbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pnamebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(catbox, 0, 218, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cidbox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(stockidbox, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(111, 111, 111)))))
                        .addContainerGap(629, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cidbox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pidbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spricebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemscostbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notebox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(stockidbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(quantitybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel19)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(slevlebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jButton8)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Add details
       
      
        String cat=catbox.getSelectedItem().toString();
        String cid= cidbox.getText();
        String pid=pidbox.getText();
        String pname=pnamebox.getText();
        String sid=stockidbox.getText();
        String quantity=quantitybox.getText();
        String stocklevel=slevlebox.getText();
        String sprice=spricebox.getText();
        String itemcost=itemscostbox.getText();
        String note=notebox.getText();
        
        SetStock_Class w =new SetStock_Class(cat,cid,pid,pname,sid,quantity,stocklevel,sprice,itemcost,note);
        w.addItems();
           
        //Table load
        try {
            re = DB.getResultSet("select * from products");
             productstable.setModel(DbUtils.resultSetToTableModel(re));
        } 
          catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Delete produts table
        int x=JOptionPane.showConfirmDialog(null,"Do you want to delete?");

        if(x==0)
        {
            String pid=pidbox.getText();
            SetStock_Class w2=new SetStock_Class(pid);
            w2.deleteProducts();
          
        }
        try {
            re = DB.getResultSet("select * from products");
             productstable.setModel(DbUtils.resultSetToTableModel(re));
        } 
          catch (Exception e) {
        }       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Update Product Table
        //update
        //yes=0
        int x=   JOptionPane.showConfirmDialog(null, "Do you want to update?");

        if(x==0)
        {
        String pid=pidbox.getText();
        String pname=pnamebox.getText();
        String sid=stockidbox.getText();
        String quantity=quantitybox.getText();
        String stocklevel=slevlebox.getText();
        String sprice=spricebox.getText();
        String itemcost=itemscostbox.getText();
        String note=notebox.getText();

            try {
              SetStock_Class w1 = new SetStock_Class(pid,pname,sid,quantity,stocklevel,sprice,itemcost,note);
            w1.updateProducts();
            
            
            } catch (Exception e) {
                System.out.println(e);
            }
        }
        
            try {
                     re = DB.getResultSet("select * from products");
                      productstable.setModel(DbUtils.resultSetToTableModel(re));
                 } 
                   catch (Exception e) {
                 }
                 
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void catboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catboxActionPerformed
      
     /* 
        String catergory=catbox.getSelectedItem().toString();
        
        try {
            SetStock_Class w1 = new SetStock_Class(catergory);
            w1.setCatid();
            
            
            } catch (Exception e) {
                System.out.println(e);
            }
 
       
       */
       
        
    }//GEN-LAST:event_catboxActionPerformed

    private void pnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameboxActionPerformed

    private void pidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidboxActionPerformed

    private void cidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidboxActionPerformed

    private void stockidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockidboxActionPerformed

    private void cmbproductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbproductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbproductsActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void quantityboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityboxActionPerformed

    private void slevleboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slevleboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slevleboxActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed

    private void spriceboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriceboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spriceboxActionPerformed

    private void itemscostboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemscostboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemscostboxActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        App.showView("rItem");
    }//GEN-LAST:event_jButton10ActionPerformed
    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
      
    }//GEN-LAST:event_jButton10MouseClicked

    private void productstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productstableMouseClicked

        
        
        /*int selectedRow = this.productstable.getSelectedRow();
        
        System.out.println(selectedRow);
        
        
        String category = this.productstable.getValueAt(selectedRow, 0)+"";
        String catId = this.productstable.getValueAt(selectedRow, 1)+"";
        
        System.out.printf("%s %s ",category,catId);
        */
        
        
        
        // Tabale component click event
        int raw=productstable.getSelectedRow();
        String cat=productstable.getValueAt(raw, 0).toString();
        String catid=productstable.getValueAt(raw, 1).toString();
        String pid=productstable.getValueAt(raw, 2).toString();
        String pname=productstable.getValueAt(raw, 3).toString();
        String sid=productstable.getValueAt(raw, 4).toString();
        //String rlevel=productstable.getValueAt(raw, 5).toString();
        String quantity=productstable.getValueAt(raw, 5).toString();
        String slevel=productstable.getValueAt(raw, 6).toString();
        String sprice=productstable.getValueAt(raw, 7).toString();
        String cost=productstable.getValueAt(raw, 8).toString();
        String note=productstable.getValueAt(raw, 9).toString();

        catbox.setSelectedItem(cat);
        cidbox.setText(catid);
        pidbox.setText(pid);
        pnamebox.setText(pname);
        stockidbox.setText(sid);
        quantitybox.setText(quantity);
        slevlebox.setText(slevel);
        spricebox.setText(sprice);
        itemscostbox.setText(cost);
        notebox.setText(note);
        
        
        
    }//GEN-LAST:event_productstableMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // con = DB.getConnection();
        
        String psearcbox =cmbproducts.getSelectedItem().toString();
     
        if(psearcbox.equals("ITEM_ID"))
        {
                    try
                    {
                     String pkeybox=txtSearch.getText();
                     re = DB.getResultSet("SELECT catergory,cid,idproducts,pname,stockid,quantity,stocklevel,sprice,cost,note From products WHERE idproducts LIKE '%"+pkeybox+"%'" );
                    productstable.setModel(DbUtils.resultSetToTableModel(re));
                    }
                    catch (Exception e) 
                    {
                        JOptionPane.showMessageDialog(null,"Unable to Retrieve Data", "Error", JOptionPane.ERROR_MESSAGE);
                    }

        }
        

        else if(psearcbox.equals("ALL"))
        {
            try
                    {
                     txtSearch.setText("");
                     re = DB.getResultSet("SELECT catergory,cid,idproducts,pname,stockid,quantity,stocklevel,sprice,cost,note From products" );
                    productstable.setModel(DbUtils.resultSetToTableModel(re));
                    }
                    catch (Exception e) 
                    {
                        JOptionPane.showMessageDialog(null,"Unable to Retrieve Data", "Error", JOptionPane.ERROR_MESSAGE);
                    }
            
        }
        
        else{
            
            try
                    {
                     String pkeybox=txtSearch.getText();
                     re = DB.getResultSet("SELECT catergory,cid,idproducts,pname,stockid,quantity,stocklevel,sprice,cost,note  From products WHERE pname LIKE '%"+pkeybox+"%'" );
                    productstable.setModel(DbUtils.resultSetToTableModel(re));
                    }
                    catch (Exception e) 
                    {
                        JOptionPane.showMessageDialog(null,"Unable to Retrieve Data", "Error", JOptionPane.ERROR_MESSAGE);
                 
 
    }//GEN-LAST:event_searchButtonActionPerformed
        }
    
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Clear text fields
        cidbox.setText("");
        pidbox.setText("");
        pnamebox.setText("");
        stockidbox.setText("");
        quantitybox.setText("");
        slevlebox.setText("");
        spricebox.setText("");
        itemscostbox.setText("");
        notebox.setText("");
        //.setText("");
        //.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> catbox;
    private javax.swing.JTextField cidbox;
    private javax.swing.JComboBox<String> cmbproducts;
    private javax.swing.JTextField itemscostbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField notebox;
    private javax.swing.JTextField pidbox;
    private javax.swing.JTextField pnamebox;
    private javax.swing.JTable productstable;
    private javax.swing.JTextField quantitybox;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField slevlebox;
    private javax.swing.JTextField spricebox;
    private javax.swing.JTextField stockidbox;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void tableload() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void resetData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
